name: nextchord
description: A cross-platform chord book and MIDI controller app for musicians.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.0
  
  # Local Database
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.3.0
  
  # MIDI
  flutter_midi_command: ^0.5.3
  
  # Audio Playback
  just_audio: ^0.9.0
  
  # File Handling
  file_selector: ^0.9.0
  file_picker: ^8.0.0
  path_provider: ^2.0.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  
  # JSON serialization
  json_serializable: ^6.7.0
  
  # Utilities
  intl: ^0.18.0
  uuid: ^3.0.0
  equatable: ^2.0.5
  
  # HTTP & Web Scraping
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  # Code generation
  build_runner: ^2.4.0
  drift_dev: ^2.16.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/audio/Perc_HeadKnock_hi.wav
    - assets/audio/Perc_HeadKnock_lo.wav
